name: Test and Copy Docker Compose

on:
  #push:
    # branches:
    #   - main  
  workflow_dispatch:  # Manual trigger
     inputs:
       environment:
         description: 'where to deploy'
         type: choice
         options:
            - infrastructure
            - internal
            - test
             
jobs:
  test-and-copy:
    runs-on: [self-hosted]
    if: ${{ github.event.inputs.environment == 'test' }}
    steps:
      - run: echo " deploy on ${{ github.event.inputs.environment}} "
      # - name: Checkout code
      #   uses: actions/checkout@v2
      
      # - name: Run script
      #   run: |
      #     # Replace the command with your script execution command
      #     ./your-test-script.sh

      # - name: Copy Docker Compose file
      #   run: |
      #     # Replace 'docker-compose.yml' with your file name and destination path
      #     cp docker-compose.yml ~/
