name: Test and Copy Docker Compose

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if necessary

jobs:
  test-and-copy:
    runs-on: test  # Replace 'test' with your runner label

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Run script
      #   run: |
      #     # Replace the command with your script execution command
      #     ./your-test-script.sh

      - name: Copy Docker Compose file
        run: |
          # Replace 'docker-compose.yml' with your file name and destination path
          cp docker-compose.yml ~/home/info/
