name: Test and Copy Docker Compose

on:
  #push:
    # branches: #the branch will be the env. that we looking for
    #   - main  
  workflow_dispatch:  # Manual trigger
     inputs:
       environment:
         description: 'where to deploy'
         type: choice
         options:
            - infrastructure
            - internal
            - dmz
             
jobs:
  infrastructure:
    runs-on: [self-hosted]
    if: ${{ github.event.inputs.environment == 'infrastructure' }}
    steps:
      - run: echo " deploy on ${{ github.event.inputs.environment}} "
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Copy Docker Compose file
        run: |          
          cp docker-compose.info.yml ~/

  internal:
    runs-on: [self-hosted]
    if: ${{ github.event.inputs.environment == 'internal' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo "Deploying on internal runner"
      - name: Copy Docker Compose file
        run: |          
          cp docker-compose.internal.yml ~/

  dmz:
    runs-on: [self-hosted]
    if: ${{ github.event.inputs.environment == 'dmz' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Deploying on dmz runner"
      - name: Copy Docker Compose file
        run: |          
          cp docker-compose.dmz.yml ~/